language: java

jdk:
  - openjdk8

dist: xenial

addons:
  sonarcloud:
    # the organization key was found here: https://sonarcloud.io/account/organizations
    organization: "lrozenblyum-github"

script:
  # fixes SonarCloud warning:
  # 'Shallow clone detected during the analysis. Some files will miss SCM information.
  # This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.'
  - git fetch --unshallow --quiet
  # by default travis 'install' phase will execute
  # mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  # travis 'script' phase is by default: mvn test -B
  # -B means: batch-mode (no questions, no progress-related logs pollution)
  # coverage profile is needed for test coverage for sonar
  - mvn test -Pcoverage -B
  # manually switching from OpenJDK11. Travis CI doc points us to use install-jdk.sh which fails
  # xenial distributive at the moment already has OpenJDK8 + OpenJDK11 installed. Just env. vars changes seem to be needed.
  - export JAVA_HOME=/usr/local/lib/jvm/openjdk11
  - export PATH=${JAVA_HOME}/bin:$PATH
  - java -version
   # specified the project key explicitly because I didn't like the automatically generate Maven-based name (com.leokom:chess)
   # thanks to this explicit specification we're free to change Maven coordinates
  - mvn sonar:sonar -Dsonar.projectKey=leokom-chess
